<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>TestProject</RootNamespace>
        <OutputType>Library</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Configurations>Debug;Release;DebugEverything</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'DebugEverything' ">
      <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
      <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="coverlet.collector" Version="6.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
      <PackageReference Include="NETStandard.Library" Version="2.0.3" />
      <PackageReference Include="NUnit" Version="3.13.3" />
      <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FormatFactory.Main\FormatFactory.Main.csproj" />
      <ProjectReference Include="..\FormatFactory.SampleProject\SampleProject.csproj" />
      <ProjectReference Include="..\MercuryNetwork.Nacha\SampleProject.Nacha.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="EDI_SAMPLE.csv" />
      <Content Include="EDI_SAMPLE.csv">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Irvin.SystemExtensions" Version="1.2.1.1" Condition=" '$(Configuration)' != 'DebugEverything' " />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\system-extensions\SystemExtensions.Standard\SystemExtensions.Standard.csproj" Condition=" '$(Configuration)' == 'DebugEverything' " />
    </ItemGroup>

</Project>
